### ISSUE TITLE
Datenbankgröße in Objekte anzeigen

### ISSUE THREAD

**Issue by DerDoubleD** [ioBroker/ioBroker.influxdb#188]
Datenbankgröße in Objekte anzeigen

**Comment by Apollon77** [comment]
Is there a DB command to get this info? What's the benefit?

**Comment by Excodibur** [comment]
@DerDoubleD:
If you are asking for storing the total DB size in an ioBroker state or similar, I don't think this is possible, as this information cannot be retrieved from the InfluxDB via query itself. Instead you would need to look at data-folder-sizes on OS-level directly to get that information, which is out of scope for this adapter.

At most in Influx 1.x there is a `SHOW STATS` query, or an __internal_ db (https://www.influxdata.com/blog/how-to-use-the-show-stats-command-and-the-internal-database-to-monitor-influxdb/) that can be used to retrieve some system metrics for InfluxDB, like memory consumption. But you won't get consumed disk-space with it. Furthermore for Influx 2 this does not seem to exist, perhaps because the use of that feature is discouraged for production-databases anyways.

**Comment by DerDoubleD** [comment]
> Is there a DB command to get this info? What's the benefit?

I think no.

**Comment by DerDoubleD** [comment]
> @DerDoubleD: If you are asking for storing the total DB size in an ioBroker state or similar, I don't think this is possible, as this information cannot be retrieved from the InfluxDB via query itself. Instead you would need to look at data-folder-sizes on OS-level directly to get that information, which is out of scope for this adapter.
> 
> At most in Influx 1.x there is a `SHOW STATS` query, or an __internal_ db (https://www.influxdata.com/blog/how-to-use-the-show-stats-command-and-the-internal-database-to-monitor-influxdb/) that can be used to retrieve some system metrics for InfluxDB, like memory consumption. But you won't get consumed disk-space with it. Furthermore for Influx 2 this does not seem to exist, perhaps because the use of that feature is discouraged for production-databases anyways.

Thank You!
