### ISSUE TITLE
interval

### ISSUE THREAD

**Issue by adavt** [ioBroker/ioBroker.influxdb#31]
Signing up in base doesn't work in the latests versions if the minimum interval > 1000 ms is established. The latest version where it normally worked with 1.3.4

**Comment by Apollon77** [comment]
What exactly you mean? What you mean by "minimum interval"? Do you mean debounce? This has a different meaning then "Minimum interval"!!

Debounce means that a value needs to be stable=unchanged for at least this time before it gets logged. So if you use 1000ms there and your values are updated fater then that you will never get a logging because valueas are all consideres instable.

Can you show your configuration as screenshot or so and show what you mean?

**Comment by adavt** [comment]
Yes, De-bounce interval(ms). When the value 1000 (default) is established everything works normally. At increase (5000) - doesn't write to base.

**Comment by adavt** [comment]
As an example - power consumption at first with parameter 1000, then with 5000 (10:58). Data completely vanish. Then it is established 1000 again (11:00).
![1111](https://user-images.githubusercontent.com/40644067/42558469-0802cdf0-84fa-11e8-8c60-4898dbc3c03d.jpg)

**Comment by Apollon77** [comment]
Ok, I reviewed and "debounce time" means that nothing is logged until the value stays unchanged. In your case si think your values change more often then 5s, and so all values are considered "unstable" and so not logged. Choose smaller values. in netx version the field description is changed to reflect the "as designed" behaviour
