### ISSUE TITLE
GetHistory converts DateTime wrong

### ISSUE THREAD

**Issue by MK-2001** [ioBroker/ioBroker.influxdb#67]
When I use the function getHistory with this command:
```javascript
sendTo('influxdb.0', 'getHistory', {
    id: "0_userdata.0.bearWeather.rainmm", //iobroker.autogen.
    options: {
        start:      1590184800000, // 23.05.2020T00:00:00.000Z
        end:        1590271200000, // 24.05.2020T00:00:00.000Z
        step:       (24 * 60 * 60 * 1000), // needed if aggregate is not none! 86400000ms 
        aggregate: 'average' // 'average' or 'none' to get raw values
    }
}, function (result) {
    log(JSON.stringify(result), 'warn');
    for (var i = 0; i < result.result.length; i++) {
        console.log(result.result[i].val + ' ' + new Date(result.result[i].ts).toISOString());
    }
});
```

I get this log entry where are other start / end timestamps are inserted:
```log
2020-05-24 10:13:38.305 - debug: influxdb.0 (24715) SELECT mean(value) as val from "0_userdata.0.bearWeather.rainmm" WHERE time > '2020-05-21T22:00:00.000Z' AND time < '2020-05-24T22:00:00.000Z' GROUP BY time(86400000ms) fill(previous) LIMIT 2002
```

I believe the two hours difference of the timestamps are belongs to my local timezone. But on the start position there is an additional day missing. 2020-05-21T22:00:00.000Z <> 23.05.2020T00:00:00.000Z

**Comment by MK-2001** [comment]
https://github.com/ioBroker/ioBroker.influxdb/blob/527077482affe4b4cfa1293a3b6e86f11367a567/main.js#L1179

I believe this line causes the problem. I am not sure which use case are this two line for. But may be this is the correct solution?
```javascript
if (!options.start) options.start -= options.step;
if (!options.start) options.end += options.step;
```

**Comment by Apollon77** [comment]
Yes soemthing with timezones seems to be strange which need to be checked.

Regarding the code you showed:
GetHistory is optimized to deliver data to use in visualizations and charts. Because of the effect that Influxdb always return "grouped by" results to minute/second boundaries and most people do not know this AND for charts it is always better to also have one datapoint before the chart starts and one datapoint after that, so that the chart is shown correctly and not starts/end "in the middle of the chart".

I could think of an additional "rawDataSelection=true" parameter to prevent this chart optimization
