### ISSUE TITLE
Data entry on restarting the instance

### ISSUE THREAD

**Issue by xlklwr** [ioBroker/ioBroker.influxdb#81]
Everytime the instance restarts inside iobroker a copy of the last data entry is added to the table as source "influxdb".

This causes issues with creating statisics. I write the daily usage at midnight to the influxDB, every restart of iobroker or the influx db instance itself causes multiple entries with the same value - if i build a weekly or monthly sum out of the daily measurements it gets dramatically wrong. 

I don't know the reason for this, but it should be selectable.

**Comment by Apollon77** [comment]
Yes this is "intended". The adapter so logs the start and end of the "logging of data". And it is not "the last data entry", it is "the latest current value of the state". If you visualize you else have no chance to see which values were really existing but "just the same value" and which is just shown as same value because no other value existsed in between.

**Comment by Apollon77** [comment]
Configurable in 3.0.0 on GitHub https://forum.iobroker.net/topic/54756/test-adapter-influxdb-3-0-0?_=1651862740479
