### ISSUE TITLE
Cannot connect to influxdb running on specific path behind a reverse proxy

### ISSUE THREAD

**Issue by TheHendla** [ioBroker/ioBroker.influxdb#94]
Cannot connect to my influxdb running behind a reverse proxy for example:

Not configureable url:
https://myserver.mydomain.de:443/influxdb/

Working url:
Https://influx.mydomain.de:443/

please add a configuration field for path.

**Comment by TheHendla** [comment]
https://tools.ietf.org/html/rfc3986#page-22

**Comment by Excodibur** [comment]
**Some research results:**
Adding a custom path seems to be not supported by node-influx 4.x (which we currently use for Influx 1.x connections), as mentioned here: https://github.com/node-influx/node-influx/issues/156#issuecomment-231524691. We need to update to node-influx 5.x first, with supports setting a path (proof: https://github.com/node-influx/node-influx/blob/b36e25db12552fd374607ef1b930ed597d39c334/src/index.ts#L52-L55). Related ticket on our side: https://github.com/ioBroker/ioBroker.influxdb/issues/34

For Influx 2.x connections it seems to be implementable rather easy, since we connect via URL already internally.

**Comment by Apollon77** [comment]
@Excodibur Then we only support it for InfluxDB 2.x ... no issue with that

**Comment by Apollon77** [comment]
Will be implemented in 3.0 for InfluxDB 2 only

**Comment by Apollon77** [comment]
see and try https://forum.iobroker.net/topic/54756/test-adapter-influxdb-3-0-0?_=1651862740477
